version: '3.7'
services:
 php:
   build: ./docker
   ports:
   - 80:80
   volumes:
   - ./src:/var/www/html
   - ./docker/php.ini:/usr/local/etc/php/php.ini
   - ./docker/000-default.conf:/etc/apache2/sites-available/000-default.conf
   container_name: php7.4-test
   extra_hosts:
   - "host.docker.internal:host-gateway"